TexasPetroleum/TexasPetroleum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TexasPetroleum.AuthData;
using TexasPetroleum.DAL;

namespace FuelRatePredictor.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(int? id)
        {
            if(id == 1)
            {
                if (ApplicationSession.Username != "")
                {
                    ApplicationSession.Username = "";
                }
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [AuthAttribute]
        public ActionResult UserHub()
        {
            return View();
        }
    }
}

TexasPetroleum/TexasPetroleum/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TexasPetroleum.DAL;
using TexasPetroleum.ViewModels;
using static TexasPetroleum.Enums.DisplayEnums;
using System.Data.Entity;
using TexasPetroleum.AuthData;

namespace TexasPetroleum.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile

        public ActionResult Index()
        {
            return View();
        }

        [AuthAttribute]
        [HttpGet]
        public ActionResult Edit()
        {
            if (ApplicationSession.Username != "" && ApplicationSession.Username != null)
            {
                var context = new QuoteContext();
                var login = context.ClientLogins.Single(x => x.Username == ApplicationSession.Username);
                var client = context.Clients.Single(x => x.LoginId == login.Id);

                ProfileVM vm = new ProfileVM()
                {
                    Name = client.Name,
                    AddressLine1 = client.AddressLine1,
                    AddressLine2 = client.AddressLine2,
                    City = client.City,
                    StateOption = client.State == null || client.State == String.Empty ? Enums.DisplayEnums.StateOptions.AK : (StateOptions)Enum.Parse(typeof(StateOptions), client.State),
                    Zipcode = client.ZipCode
                };

                return View(vm);
            }
            return View();
        }

        [AuthAttribute]
        [HttpPost]
        public ActionResult Edit(ProfileVM model)
        {
            if (ModelState.IsValid)
            {
                var context = new QuoteContext();
                var login = context.ClientLogins.Single(x => x.Username == ApplicationSession.Username);
                var client = context.Clients.Single(x => x.LoginId == login.Id);

                client.Name = model.Name;
                client.AddressLine1 = model.AddressLine1;
                client.AddressLine2 = model.AddressLine2;
                client.City = model.City;
                client.State = model.StateOption.ToString();
                client.ZipCode = model.Zipcode;

                context.SaveChanges();

                return Redirect("/Home/UserHub");
            }
            else
                return View(model);
         
        }
    }
}

TexasPetroleum/TexasPetroleum/Controllers/QuoteController.cs
using TexasPetroleum.DAL;
//using TexasPetroleum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TexasPetroleum;
using TexasPetroleum.ViewModels;
using static TexasPetroleum.Enums.DisplayEnums;
using System.Data.Entity;
using TexasPetroleum.AuthData;
using static TexasPetroleum.Enums.PricingEnums;

namespace FuelRatePredictor.Controllers
{
    public class QuoteController : Controller
    {
        // GET: Quote
        
        public ActionResult Index()
        {
            return View();
        }

        [AuthAttribute]
        [HttpGet]
        public ActionResult Edit()
        {
            if (ApplicationSession.Username != "" && ApplicationSession.Username != null)
            {
                var context = new QuoteContext();
                var login = context.ClientLogins.Single(x => x.Username == ApplicationSession.Username);
                var client = context.Clients.Single(x => x.LoginId == login.Id);

                var quote = new QuoteVM();
                quote.AddressLine1 = client.AddressLine1 == null ? "" : client.AddressLine1;
                quote.AddressLine2 = client.AddressLine2 == null ? "" : client.AddressLine2;
                quote.City = client.City == null ? "" : client.City;
                quote.State = client.State == null ? "" : client.State;
                quote.Zipcode = client.ZipCode == null ? "" : client.ZipCode;

                return View(quote);
            }
            else
            {
                return View();
            }
    
        }

        [AuthAttribute]
        [HttpPost]
        public ActionResult Edit(QuoteVM quote)
        {
            if (ModelState.IsValid)
            {
                var context = new QuoteContext();
                var login = context.ClientLogins.Single(x => x.Username == ApplicationSession.Username);
                var client = context.Clients.Single(x => x.LoginId == login.Id);
     
                FuelQuote fuelQuote = new FuelQuote();

                fuelQuote.DeliveryDate = quote.DeliveryDate;
                fuelQuote.GallonsRequested = quote.GallonsRequested;
                fuelQuote.Client = client;
                fuelQuote.TotalPrice = quote.TotalPrice;
                fuelQuote.SuggestedPrice = quote.SuggestedPrice;
               

                client.FuelQuotes.Add(fuelQuote);
                context.FuelQuotes.Add(fuelQuote);
                context.SaveChanges();

                return Redirect("/Home/UserHub");
            }
            else
            {
                return View(quote);
            }
        }

        [AuthAttribute]
        public ActionResult QuoteHistory()
        {
            if (ApplicationSession.Username != "" && ApplicationSession.Username != null)
            {
                var context = new QuoteContext();
                var login = context.ClientLogins.Single(x => x.Username == ApplicationSession.Username);
                var client = context.Clients.Single(x => x.LoginId == login.Id);
                
                List<FuelQuote> fuelQuotes = client.FuelQuotes.ToList();
                List<QuoteVM> history = new List<QuoteVM>();

                foreach (var quote in fuelQuotes)
                {

                    var vm = new QuoteVM
                    {
                        AddressLine1 = quote.Client == null ? "" : quote.Client.AddressLine1,
                        AddressLine2 = quote.Client == null ? "" : quote.Client.AddressLine2,
                        City = quote.Client == null ? "" : quote.Client.City,
                        State = quote.Client == null ? "" : quote.Client.State,
                        Zipcode = quote.Client == null ? "" : quote.Client.ZipCode,
                        DeliveryDate = quote.DeliveryDate.Date,
                        GallonsRequested = quote.GallonsRequested,
                        SuggestedPrice = quote.SuggestedPrice,
                        TotalPrice = quote.TotalPrice
                    };

                    history.Add(vm);
                }

                return View(history);
            }
            return View();
        }

        public double CalculateQuotePrice(double gallons, StateOptions state)
        {
            var context = new QuoteContext();
            var login = context.ClientLogins.Single(x => x.Username == ApplicationSession.Username);
            var client = context.Clients.Single(x => x.LoginId == login.Id);
            //Placeholder for Pricing Module calculations
            double pricePerGal = 1.50, marginPrice, profitFactor = 0.10, locationFactor, rateHistory, gallonFactor, rateFluct, sugPrice;
            string sMonth = DateTime.Now.ToString("MM"); //for current month to see which season we are in
            Int32.TryParse(sMonth, out int month);
            int QuoteCount = context.FuelQuotes.Count(x => x.ClientId == client.Id);

            if (state == StateOptions.TX)
                locationFactor = 0.02;
            else
                locationFactor = 0.04;

            if (QuoteCount > 0)
                rateHistory = 0.01;
            else
                rateHistory = 0.00;


            if (gallons > 1000)
                gallonFactor = 0.02;
            else
                gallonFactor = 0.03;

            if (Enum.GetName(typeof(Seasons), month) == "Summer")
                rateFluct = 0.04;
            else
                rateFluct = 0.03;

            marginPrice = pricePerGal * (locationFactor - rateHistory + gallonFactor + profitFactor + rateFluct); //need to add rateHistory
            sugPrice = pricePerGal + marginPrice;

            return sugPrice;
        }

        [HttpPost]
        public ActionResult GetPrice(double GallonsRequested, StateOptions State)
        {
            var context = new QuoteContext();
            var login = context.ClientLogins.Single(x => x.Username == ApplicationSession.Username);
            var client = context.Clients.Single(x => x.LoginId == login.Id);
            var user = new QuoteVM();
            user.AddressLine1 = client.AddressLine1;
            user.AddressLine2 = client.AddressLine2;
            user.City = client.City;
            user.State = client.State;
            user.Zipcode = client.ZipCode;
            user.SuggestedPrice = Math.Round(CalculateQuotePrice(GallonsRequested, State), 2);
            user.TotalPrice = Math.Round(GallonsRequested * user.SuggestedPrice, 2);
            return Json(user, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SubmitSuccess()
        {
            return View();
        }
    }
}

TexasPetroleum/TexasPetroleum/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@* Big header *@
<section class="homepg-jumbotron jumbotron text-white bg-gradient-primary">
    <div class="container">
        <h1 class="display-4">Texas Petroleum</h1>
        <p>Help us help you with the best rate on the same fuel our competitors sell at an inflated price.</p>
    </div>
</section>

@* Our grid system *@
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-xl-4 col-sm-6">
                <div class="card">
                    <img src="@Url.Content("~/Media/fuel-truck.jpg")" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Shipping</h5>
                        <p class="card-text">We ship to you! Register to become a client today.</p>
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-sm-6">
                <div class="card">
                    <img src="@Url.Content("~/Media/gas-station.jpg")" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Rate Prediction Tool</h5>
                        <p class="card-text">Our clients have access to a fuel-rate prediction tool to help you to make better financial decisions for your establishment.</p>
                        @Html.ActionLink("Register Now", "Register", "Account", null, new { id = "registerLink", @class = "btn btn-sm btn-outline-success" })
                        @Html.ActionLink("Log in", "Login", "Account", null, new { id = "loginlink", @class = "btn btn-sm btn-outline-success" })
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-sm-6">
                <div class="card">
                    <img src="@Url.Content("/Media/jet-fuel.jpg")" alt="" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">Aviation Fuel Available</h5>
                        <p class="card-text">On top of the various octane levels offered for automotive gas stations, we also offer 100-octane aviation fuel</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

TexasPetroleum/TexasPetroleum/Views/Home/UserHub.cshtml
@{
    ViewBag.Title = "UserHub";
}


<h1 class="justify-content-center">Client Hub</h1>


@* Our grid system *@
<section>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-xl-4">
                <div class="card">
                    <img src="../Media/silhouette.jpg" alt="" class="card-img-top">
                    <div class="card-body">
                        <h3 class="card-title">Profile Management</h3>
                        <p class="card-text">Manage your company's profile.</p>
                        @Html.ActionLink("Manage Profile", "Edit", "Profile", null, new { @class = "btn btn-lg btn-outline-success" })
                    </div>
                </div>
            </div>
        
        
            <div class="col-xl-4">
                <div class="card h-100">
                    <img src="../Media/handing-folder.jpg" alt="" class="card-img-top h-25">
                    <div class="card-body">
                        <h3 class="card-title">Online Quote</h3>
                        <p class="card-text">Fill out an online fuel quote form..</p>
                        @Html.ActionLink("Fill Out Online Form", "Edit", "Quote", null, new { @class = "btn btn-lg btn-outline-success" })
                    </div>
                </div>
            </div>
        
        
            <div class="col-xl-4">
                <div class="card">
                    <img src="../Media/files.jpg" alt="" class="card-img-top">
                    <div class="card-body">
                        <h3 class="card-title">Quote History</h3>
                        <p class="card-text">A record of all of your previous quotes.</p>
                        @Html.ActionLink("View Quote History", "QuoteHistory", "Quote", null, new { @class = "btn btn-lg btn-outline-success" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>